### ISSUE TITLE
В ссылках непонятное творится

### ISSUE THREAD

**Issue by vasia123** [bezumkin/Docs#140]
У меня при переходе на страницу http://docs.modx.pro/components/pdotools/snippets/pdopage выводится страница "О проекте", а по адресу http://docs.modx.pro/components/pdotools/snippets/pdousers выводится страница "Pdopage" - это так и задумано?

**Comment by bezumkin** [comment]
В скрипт импорта вкралась забавная ошибка.

Поправил, спасибо!
