### ISSUE TITLE
 Is it possible to pass more than one customvalue to the Where element of the code

### ISSUE THREAD

**Issue by jonwallacedesign** [bezumkin/Docs#179]
Hi, I am using pdoTools pdoUser to return users from MODx using the code below:

[[!pdoUsers?
     &groups=`Partners`
     &xtpl=`partnerTpl`
     &sortby=`id`
     &sortdir=`asc`
    &limit=`3`
    &where=`{"modUserProfile.extended:LIKE":"%\"customField1\":\"Value\"%"}`
    &showLog=`1`
]]

This works well, My questions is... Is it possible to pass more than one customvalue to the Where element of the code? e.g. to search more than one of the custom fields for the searched value. e.g.
	
&where=`{"modUserProfile.extended:LIKE":"%\"customField1,customField2\":\"Value\"%"}`

Please advise on how to achieve this...

**Comment by bezumkin** [comment]
This is repository with documentation, it is not the Q&A, sorry.

You can ask your question in our community https://modx.pro, I will try to help you there.

**Comment by jonwallacedesign** [comment]
OK thanks, sorry I can't understand the content on https://modx.pro - even when I put it into English it is all still in Russian? Any chance I could drop you an email re: this? Hoping that pass more than one customField is easily possible?

**Comment by bezumkin** [comment]
The content of the site on russian because people write on russian.

If you ask your question on english - you will receive answer on english.

**Comment by jonwallacedesign** [comment]
OK, I cant even seem to find the ask a question button though!

**Comment by bezumkin** [comment]
Maybe it too complicated for foreign people.

Okay, try to read [MODX docs about query conditions](https://rtfm.modx.com/xpdo/2.x/class-reference/xpdoquery/xpdoquery.where) and then apply this
```
[!pdoUsers?
    &groups=`Partners`
    &xtpl=`partnerTpl`
    &sortby=`id`
    &sortdir=`asc`
    &limit=`3`
    &where=`{
        "modUserProfile.extended:LIKE": "%\"customField1\":\"Value\"%",
        "OR:modUserProfile.extended:LIKE": "%\"customField2\":\"Value2\"%",
    }`
    &showLog=`1`
]]
```

Because it is a JSON array you will can not to specify more then one OR condition. The next one will overwrite the previous one as is array keys.

But you can use plain SQL query.
```
&where=`["
        "modUserProfile.extended LIKE '%\"customField1\":\"Value\"%' OR
        modUserProfile.extended LIKE '%\"customField2\":\"Value2\"%' OR
        modUserProfile.extended LIKE '%\"customField3\":\"Value3\"%'
"]`
```

There can be typos so control your query in showLog=1.

**Comment by jonwallacedesign** [comment]
Thanks, Tried both approaches - but they both seem to get ignored with all users being returned rather than the CustomFields being filtered

**Comment by jonwallacedesign** [comment]
This aproach works!

&where=`{"modUserProfile.extended:LIKE":"%\"customField1\":\"Value\"%","OR:modUserProfile.extended:LIKE":"%\"customField2\":\"Value\"%"}`

Many thanks ;)

**Comment by jonwallacedesign** [comment]
Can I use OR lots of times by the way? so can I check the values of say 10 fields in the Where option?
