### ISSUE TITLE
Дополнение в документацию по pdoResources

### ISSUE THREAD

**Issue by shectermen** [bezumkin/Docs#187]
&tplCondition - Поле ресурса, из которого будет получено значение для выбора чанка по условию в &conditionalTpls. Это может быть любое поле , такое как template , pagetitle и т.п , чтобы указать ТВ нужно писать его с префиксом , типа :  &tplCondition=`tv.my_tvname`

**Comment by bezumkin** [comment]
Нужно отправить pull-request.

Сделать это очень просто, [прямо через интерфейс GitHub](https://help.github.com/articles/editing-files-in-another-user-s-repository/).
