### ISSUE TITLE
mSocial

### ISSUE THREAD

**Issue by DevPastet** [bezumkin/Docs#189]
Расширение реализует основу для постинга в соцсети. В основной набор входит только Twitter.

##Как настроить mSocial?
* Устанавливаем расширение.
* Регистрируемся в Twitter, авторизовываемся.
* Регистрируем приложение [здесь](https://apps.twitter.com/ "Twitter Apps").
* Жмем кнопочку Create New App и заполняем простую форму.
* После создания приложения переходим на вкладку Keys and Access Tokens и жмем кнопку Create my access token.  **Важно**:в поле Access Level должно стоять значение Read and write. Копируем поля: Consumer Key, Consumer Secret, Access Token, Access Token Secret.

[![](https://file.modx.pro/files/1/1/8/118dc35db2127bd1a16c557a8b86e0e0s.jpg)](https://file.modx.pro/files/1/1/8/118dc35db2127bd1a16c557a8b86e0e0.png)

* Теперь открываем наш сайт. Переходим в Системные настройки / mSocial.

[![](https://file.modx.pro/files/e/7/a/e7a3b081010c426a93bc7602bd63ab66s.jpg)](https://file.modx.pro/files/e/7/a/e7a3b081010c426a93bc7602bd63ab66.png)

* Открываем чанк tpl.msocial.tw или тот который используется для постинга, вносим нужные параметры для постинга. Пример: [[+pagetitle]] - [[+content]]

* Теперь осталось только включить tv-параметр twPost для тех шаблонов, документы которых должны участвовать в постинге. Постинг происходит при сохранении ресурса, в том случае если tv-параметр twPost переключен на Да.

## Системные настройки

Имя  | По умолчанию | Описание
------------- | ------------- | -------------
msocial_tt_ot  | Пусто |  Access Token для Twitter
msocial_tw_ck | Пусто |  Consumer Key (API Key) для Twitter
msocial_tw_cs  | Пусто | Consumer Secret (API Secret) для Twitter
msocial_tw_os |  Пусто  |  Access Token Secret для Twitter
msocial_tw_tp |  tpl.msocial.tw  |  Чанк шаблона для постинга в Twitter
msocial_im_ps |  0  |  Дополнять ли посты в соцсети изображениями на основе парсинга поста (те если сообщение содержит изображения они будут прикреплены к посту, при условии что данный параметр переключен на Да).

## Содержимое компонента
* Плагины  
*mSocial* - производит постинг в соцсети.
* TVs  
*twPost* - tv для отслеживания постинга в Twitter.
* Чанки  
*tpl.msocial.tw* - шаблон для постинга в Twitter.  
Список поддерживаемых полей:  id, type, contentType, pagetitle, longtitle, description, alias, link_attributes, published, pub_date, unpub_date, parent, isfolder, introtext, content, richtext, template, menutitle, publishedby, publishedon, menuindex, hidemenu, class_key, context_key, content_type.  
**TV поля не поддерживаются, пока :)**  
		
##Информация о прикрепляемых изображениях для Twitter.
		
Для того что бы изображения корректно загружались нужно что бы они присутствовали в теле сообщения, в виде &lt;img src="путь до изображения"/&gt;. Например можно вставлять изображения в тело поля content с помощью редактора TinyMCE. Путь к изображению должен быть следующего вида files/mSocial.jpg. 
		
Twitter поддерживаются следующие форматы: PNG, JPEG, WEBP и GIF. 
С требованиями к изображениям можно ознакомиться здесь: https://dev.twitter.com/rest/public/uploading-media.

**Comment by bezumkin** [comment]
Нужно отправить pull-request.

Сделать это очень просто, [прямо через интерфейс GitHub](https://help.github.com/articles/creating-new-files/).
