### ISSUE TITLE
Не полная документация.

### ISSUE THREAD

**Issue by Boshnik** [bezumkin/Docs#511]
[Страницы в документации](https://docs.modx.pro/komponentyi/googlesheets/eksport/tovaryi) не соответствуют [страницам на гите](https://github.com/bezumkin/Docs/blob/master/ru/01_%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B/60_GoogleSheets/03_%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D1%80%D1%82/03_%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D1%8B.md).

После строки "Класс gsProduct генерирует следующие события:" пусто, а должен быть текст.

**Comment by bezumkin** [comment]
Попробуй оформить код в соответствии с [требованиями](https://github.com/bezumkin/Docs/blob/master/Contributing.md)

**Comment by Ibochkarev** [comment]
https://github.com/bezumkin/Docs/commit/607634dd0de1b9eb116da446182ea47ad7f1a75d

**Comment by Ibochkarev** [comment]
@Boshnik Саша, я проверил и исправил все ошибки синтаксиса в документации компонента.

**Comment by Boshnik** [comment]
@Ibochkarev Спасибо
