### ISSUE TITLE
Не работает HybridAuth с Vkontakte

### ISSUE THREAD

**Issue by FilenkovMaxim** [bezumkin/Docs#533]
Здравствуйте! 
Спасибо вам за вашу работу!

На данный момент не работает плагин HybridAuth в связке с Вконтакте.
Для начала как минимум плагин генерирует неправильный редирект урл, у вконтакте (как минимум на данный момент) нельзя задать урл с ? в поле "доверенный redirect url". В результате вконтакте выдает сообщение о неправильном редирект урле и не работает.

Я попробовал решить эту проблему, прописал урл /havkontakte, на своей стороне настроил редирект в .htaccess и заменил в файле /core/components/hybridauth/model/hybridauth/lib/Provider_Adapter.php строку 162

`$this->params["login_done"] = $HYBRID_AUTH_URL_BASE . ( strpos($HYBRID_AUTH_URL_BASE, '?') ? '&' : '?' ) . "hauth_done={$this->id}";`

на 
```
if($this->id === 'Vkontakte')
	       	$this->params["login_done"] = $HYBRID_AUTH_URL_BASE . 'havkontakte';
        else
	    	$this->params["login_done"]  = $HYBRID_AUTH_URL_BASE . ( strpos( $HYBRID_AUTH_URL_BASE, '?' ) ? '&' : '?' ) . "hauth.done={$this->id}";
```

Вконтакте перестал ругаться, но теперь после возвращения на сайт я вижу опять блок login. 
То есть сама аутентификация не происходит. 

Как минимум надо исправить генерацию урла для вк и перепроверить работоспособность плагина в целом.
Было бы круто выложить где-то работающий пример.

**Comment by Ibochkarev** [comment]
@FilenkovMaxim данный репозиторий для документации, а не репозиторий данного компонента. Вы можете написать о своей проблеме на modx.pro и @biz87 поправит, если это нужно сделать.
